### ISSUE TITLE
time.clock() had been removed by Python 3.8

### ISSUE THREAD

**Issue by WordlessEcho** [rinkky/xbox-download-host#6]
See: [What’s New In Python 3.8 — Python 3.8.3 documentation](https://docs.python.org/3/whatsnew/3.8.html#api-and-feature-removals)
```Python3
Traceback (most recent call last):
  File ".\run.py", line 59, in <module>
    main()
  File ".\run.py", line 40, in main
    speed = xbox.download_speed(ip)
  File "C:\Files\xbox-download-host\xbox\__init__.py", line 15, in download_speed
    start = time.clock()
AttributeError: module 'time' has no attribute 'clock'
```

**Comment by rinkky** [comment]
Fixed in latest commit.
Thank you for reporting!
